{% set version = "6.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  fn: roxygen2_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/roxygen2_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/roxygen2/roxygen2_{{ version }}.tar.gz
  sha256: 4af522cf79beebf96e591b8caf1465018e91310d12bb1a39a2cbed153499294a

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-r6
    - r-rcpp
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-stringi
    - r-stringr >=0.5
    - r-xml2

  run:
    - r-base
    - r-r6
    - r-rcpp
    - r-brew
    - r-commonmark
    - r-desc
    - r-digest
    - r-stringi
    - r-stringr >=0.5
    - r-xml2

test:
  commands:
    - $R -e "library('roxygen2')"  # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

about:
  home: https://github.com/klutometis/roxygen
  license: GPL (>= 2)
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially
    formatted comments. Writing documentation in-line with code makes it easier to keep
    your documentation up-to-date as your requirements change. 'Roxygen2' is inspired
    by the 'Doxygen' system for C++.
  license_family: GPL3
extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
