{% set version = "7.3.2" %} 
{% set posix = 'm2-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/roxygen2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/roxygen2/roxygen2_{{ version }}.tar.gz
  sha256: b788879f9132b7e2e656f442a6c592314676a9bf32d6a0a56e156cfa1ada011c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-brew                     # [build_platform != target_platform]
    - r-desc                     # [build_platform != target_platform]
    - r-stringr                  # [build_platform != target_platform]
    - r-xml2                     # [build_platform != target_platform]
    - r-digest                   # [build_platform != target_platform]
    - r-r6                       # [build_platform != target_platform]
    - r-cpp11                    # [build_platform != target_platform]
    - r-commonmark               # [build_platform != target_platform]
    - r-knitr                    # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-stringi                  # [build_platform != target_platform]
    - r-pkgload                  # [build_platform != target_platform]
    - r-purrr                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.1.2
    - r-brew
    - r-commonmark
    - r-cpp11
    - r-desc >=1.2.0
    - r-digest
    - r-knitr
    - r-pkgload >=1.0.2
    - r-purrr >=0.3.3
    - r-rlang
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2
  run:
    - r-base
    - r-r6 >=2.1.2
    - r-brew
    - r-commonmark
    - r-cpp11
    - r-desc >=1.2.0
    - r-digest
    - r-knitr
    - r-pkgload >=1.0.2
    - r-purrr >=0.3.3
    - r-rlang
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2

test:
  commands:
    - $R -e "library('roxygen2')"           # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

about:
  home: https://github.com/klutometis/roxygen
  license: MIT
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially formatted comments. Writing documentation in-line with code makes it easier to keep your documentation up-to-date as your requirements change. 'Roxygen2' is inspired by the 'Doxygen' system for C++.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
