{% set version = "7.1.2" %} 
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/roxygen2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/roxygen2/roxygen2_{{ version }}.tar.gz
  sha256: b3693d1eb57bb1c27134447ea7f64c353c085dd2237af7cfacc75fca3d2fc5fd

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.1.2
    - r-brew
    - r-commonmark
    - r-cpp11
    - r-desc >=1.2.0
    - r-digest
    - r-knitr
    - r-pkgload >=1.0.2
    - r-purrr >=0.3.3
    - r-rlang
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r6 >=2.1.2
    - r-brew
    - r-commonmark
    - r-cpp11
    - r-desc >=1.2.0
    - r-digest
    - r-knitr
    - r-pkgload >=1.0.2
    - r-purrr >=0.3.3
    - r-rlang
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2

test:
  commands:
    - $R -e "library('roxygen2')"           # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

about:
  home: https://github.com/klutometis/roxygen
  license: MIT
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially formatted comments. Writing documentation in-line with code makes it easier to keep your documentation up-to-date as your requirements change. 'Roxygen2' is inspired by the 'Doxygen' system for C++.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - mfansler
    - conda-forge/r
